In [126]:
import requests
import pandas as pd

link = 'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'


html = requests.get(link).content
df_list = pd.read_html(html)
df = df_list[0]
df.drop(df.loc[df['Borough']=='Not assigned'].index, inplace=True)
df["Neighborhood"].replace({"Not assigned": df['Borough']}, inplace=True)
df.shape

df.sort_values(by=['Postal Code'])

<bound method NDFrame.head of     Postal Code           Borough  \
2           M3A        North York
3           M4A        North York
4           M5A  Downtown Toronto
5           M6A        North York
6           M7A  Downtown Toronto
..          ...               ...
160         M8X         Etobicoke
165         M4Y  Downtown Toronto
168         M7Y      East Toronto
169         M8Y         Etobicoke
178         M8Z         Etobicoke

                                          Neighborhood
2                                            Parkwoods
3                                     Victoria Village
4                            Regent Park, Harbourfront
5                     Lawrence Manor, Lawrence Heights
6          Queen's Park, Ontario Provincial Government
..                                                 ...
160      The Kingsway, Montgomery Road, Old Mill North
165                               Church and Wellesley
168  Business reply mail Processing Centre, South C...
169  Old Mill South, King's Mill Park, Sunnylea, Hu...
178  Mimico NW, The Queensway West, South of Bloor,...

[103 rows x 3 columns]>

1) Applied pandas method to read a table directly from html via requests library;
2) Dropped the columns where borough was not assigned;
3) For the cells with not assigned neighborhood replaced the values with borough.

In [121]:
import pandas as pd


data = pd.read_csv('https://cocl.us/Geospatial_data')
data.sort_values(by=['Postal Code'])

    Postal Code   Latitude  Longitude
0           M1B  43.806686 -79.194353
1           M1C  43.784535 -79.160497
2           M1E  43.763573 -79.188711
3           M1G  43.770992 -79.216917
4           M1H  43.773136 -79.239476
..          ...        ...        ...
98          M9N  43.706876 -79.518188
99          M9P  43.696319 -79.532242
100         M9R  43.688905 -79.554724
101         M9V  43.739416 -79.588437
102         M9W  43.706748 -79.594054

[103 rows x 3 columns]

In [128]:
df_merge_col = pd.merge(data, df, on='Postal Code')
df_merge_col

,Postal Code,Latitude,Longitude,Borough,Neighborhood
0,M1B,43.806686,-79.194353,Scarborough,"Malvern, Rouge"
1,M1C,43.784535,-79.160497,Scarborough,"Rouge Hill, Port Union, Highland Creek"
2,M1E,43.763573,-79.188711,Scarborough,"Guildwood, Morningside, West Hill"
3,M1G,43.770992,-79.216917,Scarborough,Woburn
4,M1H,43.773136,-79.239476,Scarborough,Cedarbrae
...,...,...,...,...,...
98,M9N,43.706876,-79.518188,York,Weston
99,M9P,43.696319,-79.532242,Etobicoke,Westmount
100,M9R,43.688905,-79.554724,Etobicoke,"Kingsview Village, St. Phillips, Martin Grove ..."
101,M9V,43.739416,-79.588437,Etobicoke,"South Steeles, Silverstone, Humbergate, Jamest..."
102,M9W,43.706748,-79.594054,Etobicoke,"Northwest, West Humber - Clairville"